#define TOKEN_SEMICOLON                        1
#define TOKEN_QUESTIONMARK                     2
#define TOKEN_AND                              3
#define TOKEN_OR                               4
#define TOKEN_EQUAL                            5
#define TOKEN_NOT_EQUAL                        6
#define TOKEN_GREATER                          7
#define TOKEN_GREATER_EQUAL                    8
#define TOKEN_LESS                             9
#define TOKEN_LESS_EQUAL                      10
#define TOKEN_PLUS                            11
#define TOKEN_MINUS                           12
#define TOKEN_MULTIPLY                        13
#define TOKEN_DIVIDE                          14
#define TOKEN_EXP                             15
#define TOKEN_NOT                             16
#define TOKEN_IDENTIFIER                      17
#define TOKEN_VALUE                           18
#define TOKEN_LEFT_SQUARE                     19
#define TOKEN_RIGHT_SQUARE                    20
#define TOKEN_LEFT_ROUND                      21
#define TOKEN_RIGHT_ROUND                     22
#define TOKEN_COLON                           23
#define TOKEN_COMMA                           24
#define TOKEN_ASSIGN                          25
#define TOKEN_ARROW                           26
#define TOKEN_LEFT_CURLY                      27
#define TOKEN_RIGHT_CURLY                     28
#define TOKEN_DOLLAR                          29
#define TOKEN_MODEL_NAME                      30
#define TOKEN_INCLUDE                         31
