#define TOKEN_SEMICOLON                        1
#define TOKEN_AND                              2
#define TOKEN_OR                               3
#define TOKEN_EQUAL                            4
#define TOKEN_NOT_EQUAL                        5
#define TOKEN_GREATER                          6
#define TOKEN_GREATER_EQUAL                    7
#define TOKEN_LESS                             8
#define TOKEN_LESS_EQUAL                       9
#define TOKEN_PLUS                            10
#define TOKEN_MINUS                           11
#define TOKEN_MULTIPLY                        12
#define TOKEN_DIVIDE                          13
#define TOKEN_EXP                             14
#define TOKEN_NOT                             15
#define TOKEN_IDENTIFIER                      16
#define TOKEN_VALUE                           17
#define TOKEN_LEFT_ROUND                      18
#define TOKEN_RIGHT_ROUND                     19
#define TOKEN_ASSIGN                          20
#define TOKEN_LEFT_SQUARE                     21
#define TOKEN_RIGHT_SQUARE                    22
#define TOKEN_ARROW                           23
#define TOKEN_COMMA                           24
